site_name: The Bash Hackers Wiki

theme:
  name: material
  features:
    - navigation.tabs

plugins:
  - tags:
      tags_file: tags.md

markdown_extensions:
  - admonition

nav:
  - Start: index.md
  - tags.md